[project]
name = "uv-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "nekoreb", email = "bai.tn@icloud.com" }]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
uv-demo = "uv_demo.cli:main"

[build-system]
requires = ["uv_build>=0.11.32,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "ruff>=0.16.0",
]
